Traceback (most recent call last):
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 10, in verify_create_dir
    os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'TFF/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 26, in main
    verify_create_dir(path)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 12, in verify_create_dir
    os.mkdir(path) 	
FileExistsError: [Errno 17] File exists: 'TFF/'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    train_type = train_type)
  File "main.py", line 100, in main
    X_train, y_train, X_test, y_test, n_att = import_all_data(files_wav75_FF,1, 1-train_percent, balance, train_type)
  File "/root/mpi_projects/icaro/SleepEEG/Exp/input_output.py", line 50, in import_all_data
    csvfile = open(file_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_75/wav75_ex1_Filtered.csv'
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py:428: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
/root/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py:430: RuntimeWarning: invalid value encountered in true_divide
  (self.sigma_[i, :]), 1)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
