['gp_teste2_1.py', '300', '300', '20', '3', '0']
['gp_teste2_1.py', '300', '300', '20', '5', '0']
Traceback (most recent call last):
  File "gp_teste2_1.py", line 346, in <module>
    input()
EOFError: EOF when reading a line
Traceback (most recent call last):
  File "gp_teste2_1.py", line 346, in <module>
    input()
EOFError: EOF when reading a line
Traceback (most recent call last):
  File "gp_teste2_1.py", line 332, in <module>
    NGEN = int(sys.argv[1])
IndexError: list index out of range
['gp_teste2_1.py', '300', '300', '20', '3', '0']
Traceback (most recent call last):
  File "gp_teste2_1.py", line 346, in <module>
    input()
OSError: [Errno 9] Bad file descriptor
['gp_teste2_1.py', '300', '300', '20', '3', '0']
Traceback (most recent call last):
  File "gp_teste2_1.py", line 346, in <module>
    input()
OSError: [Errno 9] Bad file descriptor
s_push: parser stack overflow
>> GP Feature Selection: 
>> Inicio (Execucao 5)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gp_teste2_1.py", line 357, in <module>
    FILE_NAME = filename)
  File "gp_teste2_1.py", line 274, in main
    fitnesses = list(map(toolbox.evaluate, offspring))
  File "gp_teste2_1.py", line 135, in eval_tree
    features.append(toolbox.compile(newtree))
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 481, in compile
    "DEAP will now abort.").with_traceback(traceback)
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError: DEAP : Error in tree evaluation : Python cannot evaluate a tree higher than 90. To avoid this problem, you should use bloat control on your operators. See the DEAP documentation for more information. DEAP will now abort.
s_push: parser stack overflow
>> GP Feature Selection: 
>> Inicio (Execucao 5)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gp_teste2_1.py", line 357, in <module>
    FILE_NAME = filename)
  File "gp_teste2_1.py", line 274, in main
    fitnesses = list(map(toolbox.evaluate, offspring))
  File "gp_teste2_1.py", line 135, in eval_tree
    features.append(toolbox.compile(newtree))
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 481, in compile
    "DEAP will now abort.").with_traceback(traceback)
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError: DEAP : Error in tree evaluation : Python cannot evaluate a tree higher than 90. To avoid this problem, you should use bloat control on your operators. See the DEAP documentation for more information. DEAP will now abort.
s_push: parser stack overflow
gp_teste2_1.py:92: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
>> GP Feature Selection: 
>> Inicio (Execucao 5)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gp_teste2_1.py", line 357, in <module>
    FILE_NAME = filename)
  File "gp_teste2_1.py", line 274, in main
    fitnesses = list(map(toolbox.evaluate, offspring))
  File "gp_teste2_1.py", line 135, in eval_tree
    features.append(toolbox.compile(newtree))
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 481, in compile
    "DEAP will now abort.").with_traceback(traceback)
  File "/root/anaconda3/lib/python3.6/site-packages/deap/gp.py", line 474, in compile
    return eval(code, pset.context, {})
MemoryError: DEAP : Error in tree evaluation : Python cannot evaluate a tree higher than 90. To avoid this problem, you should use bloat control on your operators. See the DEAP documentation for more information. DEAP will now abort.
